package smt.pack.entity;

import com.google.common.collect.Lists;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import net.minecraft.creativetab.CreativeTabs;

@Mod(modid = SMTEntity.MODID, name = SMTEntity.NAME, version = SMTEntity.VERSION, useMetadata = true)
public final class SMTEntity {

	public static final String
	MODID = "smt_entity",
	NAME = "SMT: Entity",
	VERSION = "0.001";

	@Mod.Instance(MODID) public static SMTEntity instance;
	@Mod.Metadata(MODID) public static ModMetadata metadata;

	@cpw.mods.fml.common.SidedProxy(modId = MODID, serverSide = "smt.pack.entity.Proxy", clientSide = "smt.pack.entity.client.Proxy")
	public static Proxy proxy;

	public static final smt.pack.entity.config.Config config = new smt.pack.entity.config.Config();
	public static final smt.pack.entity.block.Blocks block = new smt.pack.entity.block.Blocks();
	public static final smt.pack.entity.item.Items item = new smt.pack.entity.item.Items();

	public static final CreativeTabs tabEntity = new CreativeTabs("tab_entity") {
		@Override public net.minecraft.item.Item getTabIconItem() {return item.itemsEntity;}
	};

	@Mod.EventHandler
	public void preInit(cpw.mods.fml.common.event.FMLPreInitializationEvent event) {
		metadata = metadata(event.getModMetadata());
		config.main(event.getModConfigurationDirectory());
		block.init();
		item.init();
		smt.pack.entity.entity.Entites.init();
		proxy.preInit();
	}

	@Mod.EventHandler
	public void init(cpw.mods.fml.common.event.FMLInitializationEvent event) {
		proxy.init();
	}

	public ModMetadata metadata(ModMetadata metadata) {
		metadata.authorList = Lists.newArrayList("timaxa007");
		metadata.description = "SMT: Entity.";
		metadata.logoFile = "/smt_entity_logo.png";
		metadata.autogenerated = false;
		return metadata;
	}

}
