package smt.pack.entity;

import com.google.common.collect.Lists;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import net.minecraft.creativetab.CreativeTabs;

@Mod(modid = SMTEntity.MODID, name = SMTEntity.NAME, version = SMTEntity.VERSION, dependencies = "required-after:SMT|CORE", useMetadata = true)
public class SMTEntity {
	//-----------------------------------------------------------------------------------------------
	public static final String
	MODID = "SMT|ENTITY",
	NAME = "SMT: Entity",
	TAG = "smt_entity",
	VERSION = "0.001";
	//-----------------------------------------------------------------------------------------------
	@Mod.Instance(MODID) public static SMTEntity instance;
	//-----------------------------------------------------------------------------------------------
	public static smt.pack.entity.config.Config config;
	public static smt.pack.entity.block.ListBlocks blocks;
	public static smt.pack.entity.item.ListItems items;
	//-----------------------------------------------------------------------------------------------
	public static final CreativeTabs tabEntity = new CreativeTabs("tabEntity") {
		@Override public net.minecraft.item.Item getTabIconItem() {return items.itemsEntity;}
	};
	//-----------------------------------------------------------------------------------------------
	@Mod.EventHandler
	public void preInit(cpw.mods.fml.common.event.FMLPreInitializationEvent event) {
		applyMetadata(event.getModMetadata());
		config.main(event.getModConfigurationDirectory());
		blocks.init();
		items.init();
	}
	//-----------------------------------------------------------------------------------------------
	public void applyMetadata(ModMetadata meta) {
		meta.url = "http://forum.mcmodding.ru/viewtopic.php?id=4";
		meta.authorList = Lists.newArrayList("timaxa007", "Dragon2488");
		meta.description = "SMT: Entity.";
		meta.logoFile = "/smt_entity_logo.png";
		meta.autogenerated = false;
	}
	//-----------------------------------------------------------------------------------------------
}
