package smt.pack.decorative;

import com.google.common.collect.Lists;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.network.NetworkRegistry;
import net.minecraft.creativetab.CreativeTabs;

@Mod(modid = SMTDecorative.MODID, name = SMTDecorative.NAME, version = SMTDecorative.VERSION, useMetadata = true)
public final class SMTDecorative {

	public static final String
	MODID = "smt_decorative",
	NAME = "SMT: Decorative",
	VERSION = "0.001";

	@Mod.Instance(MODID) public static SMTDecorative instance;
	@Mod.Metadata(MODID) public static ModMetadata metadata;

	@cpw.mods.fml.common.SidedProxy(modId = MODID, serverSide = "smt.pack.decorative.Proxy", clientSide = "smt.pack.decorative.client.Proxy")
	public static Proxy proxy;

	public static final smt.pack.decorative.config.Config config = new smt.pack.decorative.config.Config();
	public static final smt.pack.decorative.block.Blocks block = new smt.pack.decorative.block.Blocks();
	public static final smt.pack.decorative.item.Items item = new smt.pack.decorative.item.Items();
	public static final cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper network = NetworkRegistry.INSTANCE.newSimpleChannel(MODID);

	public static final CreativeTabs tabDecorative = new CreativeTabs("tab_decorative") {
		@Override public net.minecraft.item.Item getTabIconItem() {return item.itemsDecorative;}
	};

	@Mod.EventHandler
	public void preInit(cpw.mods.fml.common.event.FMLPreInitializationEvent event) {
		metadata = metadata(event.getModMetadata());
		config.main(event.getModConfigurationDirectory());
		smt.pack.decorative.event.Events.init();
		block.init();
		item.init();
		smt.pack.decorative.tile.TileEntites.init();
		smt.pack.decorative.entity.Entites.init();
		smt.pack.decorative.network.RegisterMessage.init(network);

		proxy.preInit();
	}

	@Mod.EventHandler
	public void init(cpw.mods.fml.common.event.FMLInitializationEvent event) {
		NetworkRegistry.INSTANCE.registerGuiHandler(instance, proxy);
		proxy.init();
	}

	@Mod.EventHandler
	public void postInit(cpw.mods.fml.common.event.FMLPostInitializationEvent event) {
		proxy.postInit();
	}

	public ModMetadata metadata(ModMetadata metadata) {
		metadata.authorList = Lists.newArrayList("timaxa007");
		metadata.description = "SMT: Decorative.";
		metadata.logoFile = "/smt_decorative_logo.png";
		metadata.autogenerated = false;
		return metadata;
	}

}
