package smt.pack.decorative;

import com.google.common.collect.Lists;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import net.minecraft.creativetab.CreativeTabs;

@Mod(modid = SMTDecorative.MODID, name = SMTDecorative.NAME, version = SMTDecorative.VERSION, dependencies = "required-after:SMT|CORE", useMetadata = true)
public class SMTDecorative {
	//-----------------------------------------------------------------------------------------------
	public static final String
	MODID = "SMT|DECORATIVE",
	NAME = "SMT: Decorative",
	TAG = "smt_decorative",
	VERSION = "0.001";
	//-----------------------------------------------------------------------------------------------
	@Mod.Instance(MODID) public static SMTDecorative instance;
	//-----------------------------------------------------------------------------------------------
	public static smt.pack.decorative.config.Config config;
	public static smt.pack.decorative.block.ListBlocks blocks;
	public static smt.pack.decorative.item.ListItems items;
	//-----------------------------------------------------------------------------------------------
	public static final CreativeTabs tabDecorative = new CreativeTabs("tabDecorative") {
		@Override public net.minecraft.item.Item getTabIconItem() {return items.itemsDecorative;}
	};
	//-----------------------------------------------------------------------------------------------
	@Mod.EventHandler
	public void preInit(cpw.mods.fml.common.event.FMLPreInitializationEvent event) {
		applyMetadata(event.getModMetadata());
		config.main(event.getModConfigurationDirectory());
		blocks.init();
		items.init();
	}
	//-----------------------------------------------------------------------------------------------
	public void applyMetadata(ModMetadata meta) {
		meta.url = "http://forum.mcmodding.ru/viewtopic.php?id=4";
		meta.authorList = Lists.newArrayList("timaxa007", "Dragon2488");
		meta.description = "SMT: Decorative.";
		meta.logoFile = "/smt_decorative_logo.png";
		meta.autogenerated = false;
	}
	//-----------------------------------------------------------------------------------------------
}
