package smt.pack.player;

import com.google.common.collect.Lists;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import net.minecraft.creativetab.CreativeTabs;

@Mod(modid = SMTPlayer.MODID, name = SMTPlayer.NAME, version = SMTPlayer.VERSION, dependencies = "required-after:SMT|CORE", useMetadata = true)
public class SMTPlayer {
	//-----------------------------------------------------------------------------------------------
	public static final String
	MODID = "SMT|PLAYER",
	NAME = "SMT: Player",
	TAG = "smt_player",
	VERSION = "0.001";
	//-----------------------------------------------------------------------------------------------
	@Mod.Instance(MODID) public static SMTPlayer instance;
	//-----------------------------------------------------------------------------------------------
	public static smt.pack.player.config.Config config;
	public static smt.pack.player.block.ListBlocks blocks;
	public static smt.pack.player.item.ListItems items;
	//-----------------------------------------------------------------------------------------------
	public static final CreativeTabs tabPlayer = new CreativeTabs("tabPlayer") {
		@Override public net.minecraft.item.Item getTabIconItem() {return items.itemsPlayer;}
	};
	//-----------------------------------------------------------------------------------------------
	@Mod.EventHandler
	public void preInit(cpw.mods.fml.common.event.FMLPreInitializationEvent event) {
		applyMetadata(event.getModMetadata());
		config.main(event.getModConfigurationDirectory());
		blocks.init();
		items.init();
	}
	//-----------------------------------------------------------------------------------------------
	public void applyMetadata(ModMetadata meta) {
		meta.url = "http://forum.mcmodding.ru/viewtopic.php?id=4";
		meta.authorList = Lists.newArrayList("timaxa007", "Dragon2488");
		meta.description = "SMT: Player.";
		meta.logoFile = "/smt_player_logo.png";
		meta.autogenerated = false;
	}
	//-----------------------------------------------------------------------------------------------
}
