package smt.pack.player;

import com.google.common.collect.Lists;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.network.NetworkRegistry;
import net.minecraft.creativetab.CreativeTabs;

@Mod(modid = SMTPlayer.MODID, name = SMTPlayer.NAME, version = SMTPlayer.VERSION, useMetadata = true)
public final class SMTPlayer {

	public static final String
	MODID = "smt_player",
	NAME = "SMT: Player",
	VERSION = "0.001";

	@Mod.Instance(MODID) public static SMTPlayer instance;
	@Mod.Metadata(MODID) public static ModMetadata metadata;

	@cpw.mods.fml.common.SidedProxy(modId = MODID, serverSide = "smt.pack.player.Proxy", clientSide = "smt.pack.player.client.Proxy")
	public static Proxy proxy;

	public static final smt.pack.player.config.Config config = new smt.pack.player.config.Config();
	public static final smt.pack.player.block.Blocks block = new smt.pack.player.block.Blocks();
	public static final smt.pack.player.item.Items item = new smt.pack.player.item.Items();
	public static final cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper network = NetworkRegistry.INSTANCE.newSimpleChannel(MODID);

	public static final CreativeTabs tabPlayer = new CreativeTabs("tab_player") {
		@Override public net.minecraft.item.Item getTabIconItem() {return item.itemsPlayer;}
	};

	@Mod.EventHandler
	public void preInit(cpw.mods.fml.common.event.FMLPreInitializationEvent event) {
		metadata = metadata(event.getModMetadata());
		config.main(event.getModConfigurationDirectory());
		smt.pack.player.event.Events.init();
		block.init();
		item.init();
		smt.pack.player.network.RegisterMessage.init(network);
		proxy.preInit();
	}

	@Mod.EventHandler
	public void init(cpw.mods.fml.common.event.FMLInitializationEvent event) {
		proxy.init();
	}

	@Mod.EventHandler
	public void postInit(cpw.mods.fml.common.event.FMLPostInitializationEvent event) {
		proxy.postInit();
	}

	public ModMetadata metadata(ModMetadata metadata) {
		metadata.authorList = Lists.newArrayList("timaxa007");
		metadata.description = "SMT: Player.";
		metadata.logoFile = "/smt_player_logo.png";
		metadata.autogenerated = false;
		return metadata;
	}

}
