package smt.pack.magic;

import com.google.common.collect.Lists;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import net.minecraft.creativetab.CreativeTabs;

@Mod(modid = SMTMagic.MODID, name = SMTMagic.NAME, version = SMTMagic.VERSION, dependencies = "required-after:SMT|CORE", useMetadata = true)
public class SMTMagic {
	//-----------------------------------------------------------------------------------------------
	public static final String
	MODID = "SMT|MAGIC",
	NAME = "SMT: Magic",
	TAG = "smt_magic",
	VERSION = "0.001";
	//-----------------------------------------------------------------------------------------------
	@Mod.Instance(MODID) public static SMTMagic instance;
	//-----------------------------------------------------------------------------------------------
	public static smt.pack.magic.config.Config config;
	public static smt.pack.magic.block.ListBlocks blocks;
	public static smt.pack.magic.item.ListItems items;
	//-----------------------------------------------------------------------------------------------
	public static final CreativeTabs tabMagic = new CreativeTabs("tabMagic") {
		@Override public net.minecraft.item.Item getTabIconItem() {return items.itemsMagic;}
	};
	//-----------------------------------------------------------------------------------------------
	@Mod.EventHandler
	public void preInit(cpw.mods.fml.common.event.FMLPreInitializationEvent event) {
		applyMetadata(event.getModMetadata());
		config.main(event.getModConfigurationDirectory());
		blocks.init();
		items.init();
	}
	//-----------------------------------------------------------------------------------------------
	public void applyMetadata(ModMetadata meta) {
		meta.url = "http://forum.mcmodding.ru/viewtopic.php?id=4";
		meta.authorList = Lists.newArrayList("timaxa007", "Dragon2488");
		meta.description = "SMT: Magic.";
		meta.logoFile = "/smt_magic_logo.png";
		meta.autogenerated = false;
	}
	//-----------------------------------------------------------------------------------------------
}
