package smt.pack.magic;

import com.google.common.collect.Lists;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.network.NetworkRegistry;
import net.minecraft.creativetab.CreativeTabs;

@Mod(modid = SMTMagic.MODID, name = SMTMagic.NAME, version = SMTMagic.VERSION, useMetadata = true)
public final class SMTMagic {

	public static final String
	MODID = "smt_magic",
	NAME = "SMT: Magic",
	VERSION = "0.001";

	@Mod.Instance(MODID) public static SMTMagic instance;
	@Mod.Metadata(MODID) public static ModMetadata metadata;

	@cpw.mods.fml.common.SidedProxy(modId = MODID, serverSide = "smt.pack.magic.Proxy", clientSide = "smt.pack.magic.client.Proxy")
	public static Proxy proxy;

	public static final smt.pack.magic.config.Config config = new smt.pack.magic.config.Config();
	public static final smt.pack.magic.block.Blocks block = new smt.pack.magic.block.Blocks();
	public static final smt.pack.magic.item.Items item = new smt.pack.magic.item.Items();
	public static final cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper network = NetworkRegistry.INSTANCE.newSimpleChannel(MODID);

	public static final CreativeTabs tabMagic = new CreativeTabs("tab_magic") {
		@Override public net.minecraft.item.Item getTabIconItem() {return item.itemsMagic;}
	};

	@Mod.EventHandler
	public void preInit(cpw.mods.fml.common.event.FMLPreInitializationEvent event) {
		metadata = metadata(event.getModMetadata());
		config.main(event.getModConfigurationDirectory());
		smt.pack.magic.event.Events.init();
		block.init();
		item.init();
		smt.pack.magic.tile.TileEntites.init();
		smt.pack.magic.entity.Entites.init();
		smt.pack.magic.network.RegisterMessage.init(network);

		proxy.preInit();
	}

	@Mod.EventHandler
	public void init(cpw.mods.fml.common.event.FMLInitializationEvent event) {
		NetworkRegistry.INSTANCE.registerGuiHandler(instance, proxy);
		proxy.init();
	}

	@Mod.EventHandler
	public void postInit(cpw.mods.fml.common.event.FMLPostInitializationEvent event) {
		proxy.postInit();
	}

	@Mod.EventHandler
	public void serverStart(cpw.mods.fml.common.event.FMLServerStartingEvent event) {
		//event.registerServerCommand(new GiveNodropCommand());
	}

	public ModMetadata metadata(ModMetadata metadata) {
		metadata.authorList = Lists.newArrayList("timaxa007");
		metadata.description = "SMT: Magic.";
		metadata.logoFile = "/smt_magic_logo.png";
		metadata.autogenerated = false;
		return metadata;
	}

}
