package smt.pack.phytology;

import com.google.common.collect.Lists;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.creativetab.CreativeTabs;
import smt.pack.phytology.world.WorldGen;

@Mod(modid = SMTPhytology.MODID, name = SMTPhytology.NAME, version = SMTPhytology.VERSION, useMetadata = true)
public final class SMTPhytology {

	public static final String
	MODID = "smt_phytology",
	NAME = "SMT: Phytology",
	VERSION = "0.001";

	@Mod.Instance(MODID) public static SMTPhytology instance;
	@Mod.Metadata(MODID) public static ModMetadata metadata;

	@cpw.mods.fml.common.SidedProxy(modId = MODID, serverSide = "smt.pack.phytology.Proxy", clientSide = "smt.pack.phytology.client.Proxy")
	public static Proxy proxy;

	public static final smt.pack.phytology.config.Config config = new smt.pack.phytology.config.Config();
	public static final smt.pack.phytology.block.Blocks block = new smt.pack.phytology.block.Blocks();
	public static final smt.pack.phytology.item.Items item = new smt.pack.phytology.item.Items();
	public static final cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper network = NetworkRegistry.INSTANCE.newSimpleChannel(MODID);

	public static final CreativeTabs tabPhytology = new CreativeTabs("tab_phytology") {
		@Override public net.minecraft.item.Item getTabIconItem() {return item.itemsPhytology;}
	};

	@Mod.EventHandler
	public void preInit(cpw.mods.fml.common.event.FMLPreInitializationEvent event) {
		metadata = metadata(event.getModMetadata());
		config.main(event.getModConfigurationDirectory());
		smt.pack.phytology.event.Events.init();
		block.init();
		item.init();

		smt.pack.phytology.network.RegisterMessage.init(network);

		GameRegistry.registerWorldGenerator(new WorldGen(), 0);
		proxy.preInit();
	}

	@Mod.EventHandler
	public void init(cpw.mods.fml.common.event.FMLInitializationEvent event) {
		proxy.init();
	}

	@Mod.EventHandler
	public void postInit(cpw.mods.fml.common.event.FMLPostInitializationEvent event) {
		proxy.postInit();
	}

	public ModMetadata metadata(ModMetadata metadata) {
		metadata.authorList = Lists.newArrayList("timaxa007");
		metadata.description = "SMT: Phytology.";
		metadata.logoFile = "/smt_phytology_logo.png";
		metadata.autogenerated = false;
		return metadata;
	}

}
