package smt.pack.technology.inventory;

public final class GuiID {
	public static final int
	BLOCKS_TECHNOLOGY = 0,
	BLOCK_ACCUMULATOR = 1,
	ELECTRIC_MACHINE = 2
	/*
	ELECTRIC_CRASHER = 2,
	ELECTRIC_FURNACE = 3,
	ELECTRIC_CRUSHER = 4,
	ELECTRIC_BREAKER = 5,
	ELECTRIC_PLACER = 6,
	ELECTRIC_MINER = 7,
	ELECTRIC_GENERATOR = 8,
	ELECTRIC_TRANSPOSER = 9,
	ELECTRIC_BUILDER = 10,
	ELECTRIC_BIG_BUFFER_ITEM = 11
	 */
	;
}
