package smt.pack.geology;

import com.google.common.collect.Lists;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import net.minecraft.creativetab.CreativeTabs;

@Mod(modid = SMTGeology.MODID, name = SMTGeology.NAME, version = SMTGeology.VERSION, dependencies = "required-after:SMT|CORE", useMetadata = true)
public class SMTGeology {
	//-----------------------------------------------------------------------------------------------
	public static final String
	MODID = "SMT|GEOLOGY",
	NAME = "SMT: Geology",
	TAG = "smt_geology",
	VERSION = "0.001";
	//-----------------------------------------------------------------------------------------------
	@Mod.Instance(MODID) public static SMTGeology instance;
	//-----------------------------------------------------------------------------------------------
	public static smt.pack.geology.config.Config config;
	public static smt.pack.geology.block.ListBlocks blocks;
	public static smt.pack.geology.item.ListItems items;
	//-----------------------------------------------------------------------------------------------
	public static final CreativeTabs tabGeology = new CreativeTabs("tabGeolog") {
		@Override public net.minecraft.item.Item getTabIconItem() {return items.itemsGeology;}
	};
	//-----------------------------------------------------------------------------------------------
	@Mod.EventHandler
	public void preInit(cpw.mods.fml.common.event.FMLPreInitializationEvent event) {
		applyMetadata(event.getModMetadata());
		config.main(event.getModConfigurationDirectory());
		blocks.init();
		items.init();
	}
	//-----------------------------------------------------------------------------------------------
	public void applyMetadata(ModMetadata meta) {
		meta.url = "http://forum.mcmodding.ru/viewtopic.php?id=4";
		meta.authorList = Lists.newArrayList("timaxa007", "Dragon2488");
		meta.description = "SMT: Geology.";
		meta.logoFile = "/smt_geology_logo.png";
		meta.autogenerated = false;
	}
	//-----------------------------------------------------------------------------------------------
}
