package smt.pack.geology;

import com.google.common.collect.Lists;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.creativetab.CreativeTabs;
import smt.pack.geology.world.WorldGen;

@Mod(modid = SMTGeology.MODID, name = SMTGeology.NAME, version = SMTGeology.VERSION, useMetadata = true)
public final class SMTGeology {

	public static final String
	MODID = "smt_geology",
	NAME = "SMT: Geology",
	VERSION = "0.001";

	@Mod.Instance(MODID) public static SMTGeology instance;
	@Mod.Metadata(MODID) public static ModMetadata metadata;

	@cpw.mods.fml.common.SidedProxy(modId = MODID, serverSide = "smt.pack.geology.Proxy", clientSide = "smt.pack.geology.client.Proxy")
	public static Proxy proxy;

	public static final smt.pack.geology.config.Config config = new smt.pack.geology.config.Config();
	public static final smt.pack.geology.block.Blocks block = new smt.pack.geology.block.Blocks();
	public static final smt.pack.geology.item.Items item = new smt.pack.geology.item.Items();
	public static final smt.pack.geology.world.Biomes biome = new smt.pack.geology.world.Biomes();

	public static final CreativeTabs tabGeology = new CreativeTabs("tab_geology") {
		@Override public net.minecraft.item.Item getTabIconItem() {return item.itemsGeology;}
	};

	@Mod.EventHandler
	public void preInit(cpw.mods.fml.common.event.FMLPreInitializationEvent event) {
		metadata = metadata(event.getModMetadata());
		config.main(event.getModConfigurationDirectory());
		smt.pack.geology.event.Events.init();
		block.init();
		item.init();
		smt.pack.geology.tile.TileEntites.init();
		biome.init();
		GameRegistry.registerWorldGenerator(new WorldGen(), 0);
		proxy.preInit();
	}

	@Mod.EventHandler
	public void init(cpw.mods.fml.common.event.FMLInitializationEvent event) {
		proxy.init();
	}

	@Mod.EventHandler
	public void postInit(cpw.mods.fml.common.event.FMLPostInitializationEvent event) {
		proxy.postInit();
	}

	public ModMetadata metadata(ModMetadata metadata) {
		metadata.authorList = Lists.newArrayList("timaxa007");
		metadata.description = "SMT: Geology.";
		metadata.logoFile = "/smt_geology_logo.png";
		metadata.autogenerated = false;
		return metadata;
	}

}
