package smt.pack.meteorology;

import com.google.common.collect.Lists;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import net.minecraft.creativetab.CreativeTabs;

@Mod(modid = SMTMeteorology.MODID, name = SMTMeteorology.NAME, version = SMTMeteorology.VERSION, useMetadata = true)
public final class SMTMeteorology {

	public static final String
	MODID = "smt_meteorology",
	NAME = "SMT: Meteorology",
	VERSION = "0.001";

	@Mod.Instance(MODID) public static SMTMeteorology instance;
	@Mod.Metadata(MODID) public static ModMetadata metadata;

	public static final smt.pack.meteorology.config.Config config = new smt.pack.meteorology.config.Config();
	public static final smt.pack.meteorology.block.Blocks block = new smt.pack.meteorology.block.Blocks();
	public static final smt.pack.meteorology.item.Items item = new smt.pack.meteorology.item.Items();

	public static final CreativeTabs tabMeteorology = new CreativeTabs("tab_meteorology") {
		@Override public net.minecraft.item.Item getTabIconItem() {return item.itemsMeteorology;}
	};

	@Mod.EventHandler
	public void preInit(cpw.mods.fml.common.event.FMLPreInitializationEvent event) {
		metadata = metadata(event.getModMetadata());
		config.main(event.getModConfigurationDirectory());
		block.init();
		item.init();
	}

	public ModMetadata metadata(ModMetadata metadata) {
		metadata.url = "http://forum.mcmodding.ru/viewtopic.php?id=4";
		metadata.authorList = Lists.newArrayList("timaxa007");
		metadata.description = "SMT: Meteorology.";
		metadata.logoFile = "/smt_meteorology_logo.png";
		metadata.autogenerated = false;
		return metadata;
	}

}
