package smt.pack.common;

import com.google.common.collect.Lists;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.network.NetworkRegistry;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import smt.pack.common.api.RegisteredItems;

//dependencies = "required-after:SMT|CORE"
@Mod(modid = SMTCommon.MODID, name = SMTCommon.NAME, version = SMTCommon.VERSION, useMetadata = true)
public final class SMTCommon {

	public static final String
	MODID = "smt_common",
	NAME = "SMT: Common",
	VERSION = "0.001";

	@Mod.Instance(MODID) public static SMTCommon instance;
	@Mod.Metadata(MODID) public static ModMetadata metadata;

	@cpw.mods.fml.common.SidedProxy(modId = MODID, serverSide = "smt.pack.common.Proxy", clientSide = "smt.pack.common.client.Proxy")
	public static Proxy proxy;

	public static final smt.pack.common.config.Config config = new smt.pack.common.config.Config();
	public static final cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper network = NetworkRegistry.INSTANCE.newSimpleChannel(MODID);

	public static final CreativeTabs tabCommon = new CreativeTabs("tab_common") {
		@Override public Item getTabIconItem() {
			return RegisteredItems.get("item_items_common").getItem();
		}
	};

	@Mod.EventHandler
	public void preInit(cpw.mods.fml.common.event.FMLPreInitializationEvent event) {
		metadata = metadata(event.getModMetadata());
		config.main(event.getModConfigurationDirectory());
		smt.pack.common.event.Events.init();
		smt.pack.common.block.Blocks.init();
		smt.pack.common.item.Items.init();
		smt.pack.common.tile.TileEntites.init();
		smt.pack.common.entity.Entites.init();
		smt.pack.common.network.RegisterMessage.init(network);
		proxy.preInit();
	}

	@Mod.EventHandler
	public void init(cpw.mods.fml.common.event.FMLInitializationEvent event) {
		NetworkRegistry.INSTANCE.registerGuiHandler(instance, proxy);
		proxy.init();
	}

	@Mod.EventHandler
	public void postInit(cpw.mods.fml.common.event.FMLPostInitializationEvent event) {
		proxy.postInit();
	}

	@Mod.EventHandler
	public void serverStart(cpw.mods.fml.common.event.FMLServerStartingEvent event) {
		//event.registerServerCommand(new ResurrectionItemCommand());
	}

	public ModMetadata metadata(ModMetadata metadata) {
		metadata.authorList = Lists.newArrayList("timaxa007");
		metadata.description = "SMT: Common.";
		metadata.logoFile = "/smt_common_logo.png";
		metadata.autogenerated = false;
		return metadata;
	}

}
