package smt.pack.common;

import com.google.common.collect.Lists;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import net.minecraft.creativetab.CreativeTabs;

@Mod(modid = SMTCommon.MODID, name = SMTCommon.NAME, version = SMTCommon.VERSION, dependencies = "required-after:SMT|CORE", useMetadata = true)
public class SMTCommon {
	//-----------------------------------------------------------------------------------------------
	public static final String
	MODID = "SMT|COMMON",
	NAME = "SMT: Common",
	TAG = "smt_common",
	VERSION = "0.001";
	//-----------------------------------------------------------------------------------------------
	@Mod.Instance(MODID) public static SMTCommon instance;
	//-----------------------------------------------------------------------------------------------
	public static smt.pack.common.config.Config config;
	public static smt.pack.common.block.ListBlocks blocks;
	public static smt.pack.common.item.ListItems items;
	//-----------------------------------------------------------------------------------------------
	public static final CreativeTabs tabCommon = new CreativeTabs("tabCommon") {
		@Override public net.minecraft.item.Item getTabIconItem() {return items.itemsCommon;}
	};
	//-----------------------------------------------------------------------------------------------
	@Mod.EventHandler
	public void preInit(cpw.mods.fml.common.event.FMLPreInitializationEvent event) {
		applyMetadata(event.getModMetadata());
		config.main(event.getModConfigurationDirectory());
		blocks.init();
		items.init();
	}
	//-----------------------------------------------------------------------------------------------
	public void applyMetadata(ModMetadata meta) {
		meta.url = "http://forum.mcmodding.ru/viewtopic.php?id=4";
		meta.authorList = Lists.newArrayList("timaxa007", "Dragon2488");
		meta.description = "SMT: Common.";
		meta.logoFile = "/smt_common_logo.png";
		meta.autogenerated = false;
	}
	//-----------------------------------------------------------------------------------------------
}
