package smt.pack.cookery;

import com.google.common.collect.Lists;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import net.minecraft.creativetab.CreativeTabs;

@Mod(modid = SMTCookery.MODID, name = SMTCookery.NAME, version = SMTCookery.VERSION, dependencies = "required-after:SMT|CORE", useMetadata = true)
public class SMTCookery {
	//-----------------------------------------------------------------------------------------------
	public static final String
	MODID = "SMT|COOKERY",
	NAME = "SMT: Cookery",
	TAG = "smt_cookery",
	VERSION = "0.001";
	//-----------------------------------------------------------------------------------------------
	@Mod.Instance(MODID)
	public static SMTCookery instance;
	//-----------------------------------------------------------------------------------------------
	public static smt.pack.cookery.config.Config config;
	public static smt.pack.cookery.block.ListBlocks blocks;
	public static smt.pack.cookery.item.ListItems items;
	//-----------------------------------------------------------------------------------------------
	public static final CreativeTabs tabCookery = new CreativeTabs("tabCookery") {
		@Override public net.minecraft.item.Item getTabIconItem() {return items.itemsCookery;}
	};
	//-----------------------------------------------------------------------------------------------
	@Mod.EventHandler
	public void preInit(cpw.mods.fml.common.event.FMLPreInitializationEvent event) {
		applyMetadata(event.getModMetadata());
		config.main(event.getModConfigurationDirectory());
		blocks.init();
		items.init();
	}
	//-----------------------------------------------------------------------------------------------
	public void applyMetadata(ModMetadata meta) {
		meta.url = "http://forum.mcmodding.ru/viewtopic.php?id=4";
		meta.authorList = Lists.newArrayList("timaxa007", "Dragon2488");
		meta.description = "SMT: Cookery.";
		meta.logoFile = "/smt_cookery_logo.png";
		meta.autogenerated = false;
	}
	//-----------------------------------------------------------------------------------------------
}
