package smt.pack.cookery;

import com.google.common.collect.Lists;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.network.NetworkRegistry;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.stats.Achievement;

@Mod(modid = SMTCookery.MODID, name = SMTCookery.NAME, version = SMTCookery.VERSION, useMetadata = true)
public final class SMTCookery {

	public static final String
	MODID = "smt_cookery",
	NAME = "SMT: Cookery",
	VERSION = "0.001";

	@Mod.Instance(MODID) public static SMTCookery instance;
	@Mod.Metadata(MODID) public static ModMetadata metadata;

	@cpw.mods.fml.common.SidedProxy(modId = MODID, serverSide = "smt.pack.cookery.Proxy", clientSide = "smt.pack.cookery.client.Proxy")
	public static Proxy proxy;

	public static final smt.pack.cookery.config.Config config = new smt.pack.cookery.config.Config();
	public static final smt.pack.cookery.block.Blocks block = new smt.pack.cookery.block.Blocks();
	public static final smt.pack.cookery.item.Items item = new smt.pack.cookery.item.Items();

	public static Achievement achievementTastyFood;
	public static Achievement achievementSweetFood;
	public static Achievement achievementSaltyFood;

	public static final CreativeTabs tabCookery = new CreativeTabs("tab_cookery") {
		@Override public net.minecraft.item.Item getTabIconItem() {return item.itemsCookery;}
	};

	@Mod.EventHandler
	public void preInit(cpw.mods.fml.common.event.FMLPreInitializationEvent event) {
		metadata = metadata(event.getModMetadata());
		config.main(event.getModConfigurationDirectory());
		block.init();
		item.init();
		smt.pack.cookery.tile.TileEntites.init();

		achievementTastyFood = new Achievement("achievement.tasty_food", "tasty_food", 10, -5, item.itemsCookery, (Achievement)null).registerStat();
		achievementSweetFood = new Achievement("achievement.sweet_food", "sweet_food", 11, -5, item.itemsCookery, (Achievement)null).registerStat();
		achievementSaltyFood = new Achievement("achievement.salty_food", "salty_food", 12, -5, item.itemsCookery, (Achievement)null).registerStat();

		proxy.preInit();
	}

	@Mod.EventHandler
	public void init(cpw.mods.fml.common.event.FMLInitializationEvent event) {
		NetworkRegistry.INSTANCE.registerGuiHandler(instance, proxy);
		proxy.init();
	}

	public ModMetadata metadata(ModMetadata metadata) {
		metadata.url = "http://forum.mcmodding.ru/viewtopic.php?id=4";
		metadata.authorList = Lists.newArrayList("timaxa007");
		metadata.description = "SMT: Cookery.";
		metadata.logoFile = "/smt_cookery_logo.png";
		metadata.autogenerated = false;
		return metadata;
	}

}
