package smt.pack.medicine;

import com.google.common.collect.Lists;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import net.minecraft.creativetab.CreativeTabs;

@Mod(modid = SMTMedicine.MODID, name = SMTMedicine.NAME, version = SMTMedicine.VERSION, dependencies = "required-after:SMT|CORE", useMetadata = true)
public class SMTMedicine {
	//-----------------------------------------------------------------------------------------------
	public static final String
	MODID = "SMT|MEDICINE",
	NAME = "SMT: Medicine",
	TAG = "smt_medicine",
	VERSION = "0.001";
	//-----------------------------------------------------------------------------------------------
	@Mod.Instance(MODID) public static SMTMedicine instance;
	//-----------------------------------------------------------------------------------------------
	public static smt.pack.medicine.config.Config config;
	public static smt.pack.medicine.block.ListBlocks blocks;
	public static smt.pack.medicine.item.ListItems items;
	//-----------------------------------------------------------------------------------------------
	public static final CreativeTabs tabMedicine = new CreativeTabs("tabMedicine") {
		@Override public net.minecraft.item.Item getTabIconItem() {return items.itemsMedicine;}
	};
	//-----------------------------------------------------------------------------------------------
	@Mod.EventHandler
	public void preInit(cpw.mods.fml.common.event.FMLPreInitializationEvent event) {
		applyMetadata(event.getModMetadata());
		config.main(event.getModConfigurationDirectory());
		blocks.init();
		items.init();
	}
	//-----------------------------------------------------------------------------------------------
	public void applyMetadata(ModMetadata meta) {
		meta.url = "http://forum.mcmodding.ru/viewtopic.php?id=4";
		meta.authorList = Lists.newArrayList("timaxa007", "Dragon2488");
		meta.description = "SMT: Medicine.";
		meta.logoFile = "/smt_medicine_logo.png";
		meta.autogenerated = false;
	}
	//-----------------------------------------------------------------------------------------------
}
