package smt.pack.medicine;

import com.google.common.collect.Lists;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import net.minecraft.creativetab.CreativeTabs;

@Mod(modid = SMTMedicine.MODID, name = SMTMedicine.NAME, version = SMTMedicine.VERSION, useMetadata = true)
public final class SMTMedicine {

	public static final String
	MODID = "smt_medicine",
	NAME = "SMT: Medicine",
	VERSION = "0.001";

	@Mod.Instance(MODID) public static SMTMedicine instance;
	@Mod.Metadata(MODID) public static ModMetadata metadata;

	public static final smt.pack.medicine.config.Config config = new smt.pack.medicine.config.Config();
	public static final smt.pack.medicine.block.Blocks block = new smt.pack.medicine.block.Blocks();
	public static final smt.pack.medicine.item.Items item = new smt.pack.medicine.item.Items();

	public static final CreativeTabs tabMedicine = new CreativeTabs("tab_medicine") {
		@Override public net.minecraft.item.Item getTabIconItem() {return item.itemsMedicine;}
	};

	@Mod.EventHandler
	public void preInit(cpw.mods.fml.common.event.FMLPreInitializationEvent event) {
		metadata = metadata(event.getModMetadata());
		config.main(event.getModConfigurationDirectory());
		block.init();
		item.init();
	}

	public ModMetadata metadata(ModMetadata metadata) {
		metadata.url = "http://forum.mcmodding.ru/viewtopic.php?id=4";
		metadata.authorList = Lists.newArrayList("timaxa007");
		metadata.description = "SMT: Medicine.";
		metadata.logoFile = "/smt_medicine_logo.png";
		metadata.autogenerated = false;
		return metadata;
	}

}
