package mods.timaxa007.Pack.Furniture;

import mods.timaxa007.Pack.Furniture.Blocks.*;
import mods.timaxa007.Pack.Furniture.Gui.HandlerGuiFurniture;
import mods.timaxa007.Pack.Furniture.Items.*;
import mods.timaxa007.Pack.Furniture.List.ListFurniture;
import mods.timaxa007.Pack.Furniture.TE.*;
import net.minecraft.block.Block;
import net.minecraft.block.BlockPane;
import net.minecraft.block.material.Material;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.EnumArmorMaterial;
import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.Configuration;
import net.minecraftforge.common.EnumHelper;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.oredict.OreDictionary;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.TickRegistry;
import cpw.mods.fml.relauncher.Side;

public class ProxyServer {

public static CreativeTabs tabFurniturePack = new TabFurniturePack(CreativeTabs.getNextID(), "tabFurniturePack");

public static EnumArmorMaterial CLOTHWOOL = EnumHelper.addArmorMaterial("CLOTHWOOL", 6, new int[] {2, 3, 2, 1}, 10);
public static EnumArmorMaterial COSTUME = EnumHelper.addArmorMaterial("COSTUME", 0, new int[] {2, 2, 2, 1}, 3);

//Blocks
public static Block block_furniture_machines;public static int block_furniture_machines_blockID;
public static Block block_cnstor_block;public static int block_cnstor_block_blockID;
public static Block block_cnstor_angle;public static int block_cnstor_angle_blockID;
public static Block block_cnstor_half;public static int block_cnstor_half_blockID;
public static Block block_cnstor_button;public static int block_cnstor_button_blockID;
public static Block block_cnstor_lever;public static int block_cnstor_lever_blockID;
public static Block block_cnstor_stairs;public static int block_cnstor_stairs_blockID;
public static Block block_cnstor_fence;public static int block_cnstor_fence_blockID;
public static Block block_cnstor_wall;public static int block_cnstor_wall_blockID;
public static Block block_cnstor_door;public static int block_cnstor_door_blockID;
public static Block block_cnstor_bed;public static int block_cnstor_bed_blockID;

public static Block air_light_0;public static int air_light_0_blockID;
public static Block air_light_1;public static int air_light_1_blockID;
public static Block air_light_2;public static int air_light_2_blockID;
public static Block air_light_3;public static int air_light_3_blockID;
public static Block air_light_4;public static int air_light_4_blockID;
public static Block air_light_5;public static int air_light_5_blockID;
public static Block air_light_6;public static int air_light_6_blockID;
public static Block air_light_7;public static int air_light_7_blockID;
public static Block air_light_8;public static int air_light_8_blockID;
public static Block air_light_9;public static int air_light_9_blockID;
public static Block air_light_10;public static int air_light_10_blockID;
public static Block air_light_11;public static int air_light_11_blockID;
public static Block air_light_12;public static int air_light_12_blockID;
public static Block air_light_13;public static int air_light_13_blockID;
public static Block air_light_14;public static int air_light_14_blockID;
public static Block air_light_15;public static int air_light_15_blockID;
public static Block air_light_16;public static int air_light_16_blockID;

public static Block block_light_0;public static int block_light_0_blockID;
public static Block block_light_1;public static int block_light_1_blockID;
public static Block block_light_2;public static int block_light_2_blockID;
public static Block block_light_3;public static int block_light_3_blockID;
public static Block block_light_4;public static int block_light_4_blockID;
public static Block block_light_5;public static int block_light_5_blockID;
public static Block block_light_6;public static int block_light_6_blockID;
public static Block block_light_7;public static int block_light_7_blockID;
public static Block block_light_8;public static int block_light_8_blockID;
public static Block block_light_9;public static int block_light_9_blockID;
public static Block block_light_10;public static int block_light_10_blockID;
public static Block block_light_11;public static int block_light_11_blockID;
public static Block block_light_12;public static int block_light_12_blockID;
public static Block block_light_13;public static int block_light_13_blockID;
public static Block block_light_14;public static int block_light_14_blockID;
public static Block block_light_15;public static int block_light_15_blockID;
public static Block block_light_16;public static int block_light_16_blockID;

public static Block block_lamps_click_on;public static int block_lamps_click_on_blockID;
public static Block block_lamps_click_off;public static int block_lamps_click_off_blockID;
public static Block block_lamps_on;public static int block_lamps_on_blockID;
public static Block block_lamps_off;public static int block_lamps_off_blockID;
public static Block block_lamps_on_invert;public static int block_lamps_on_invert_blockID;
public static Block block_lamps_off_invert;public static int block_lamps_off_invert_blockID;
public static Block block_model_lamps_click_on;public static int block_model_lamps_click_on_blockID;
public static Block block_model_lamps_click_off;public static int block_model_lamps_click_off_blockID;
public static Block block_model_lamps_on;public static int block_model_lamps_on_blockID;
public static Block block_model_lamps_off;public static int block_model_lamps_off_blockID;
public static Block block_model_lamps_on_invert;public static int block_model_lamps_on_invert_blockID;
public static Block block_model_lamps_off_invert;public static int block_model_lamps_off_invert_blockID;
public static Block block_model_lamps2_click_on;public static int block_model_lamps2_click_on_blockID;
public static Block block_model_lamps2_click_off;public static int block_model_lamps2_click_off_blockID;
public static Block block_model_lamps2_on;public static int block_model_lamps2_on_blockID;
public static Block block_model_lamps2_off;public static int block_model_lamps2_off_blockID;
public static Block block_model_lamps2_on_invert;public static int block_model_lamps2_on_invert_blockID;
public static Block block_model_lamps2_off_invert;public static int block_model_lamps2_off_invert_blockID;
public static Block block_stone_colona1_colors;public static int block_stone_colona1_colors_blockID;
public static Block block_stone_colona2_colors;public static int block_stone_colona2_colors_blockID;
public static Block block_stone_colona3_colors;public static int block_stone_colona3_colors_blockID;
public static Block block_stone_colona4_colors;public static int block_stone_colona4_colors_blockID;
public static Block block_candle;public static int block_candle_blockID;
public static Block block_candle_light;public static int block_candle_light_blockID;
public static Block block_crystals;public static int block_crystals_blockID;
public static Block block_barrels;public static int block_barrels_blockID;
public static Block block_bookshelf;public static int block_bookshelf_blockID;
public static Block block_table;public static int block_table_blockID;
public static Block block_chair;public static int block_chair_blockID;
public static Block block_wardrobe;public static int block_wardrobe_blockID;
public static Block block_mincer;public static int block_mincer_blockID;
public static Block block_arm_chair;public static int block_arm_chair_blockID;
public static Block block_blender;public static int block_blender_blockID;
public static Block block_grills;public static int block_grills_blockID;
public static Block block_box_particles;public static int block_box_particles_blockID;
public static Block block_balls;public static int block_balls_blockID;
public static Block block_bonfires;public static int block_bonfires_blockID;
public static Block block_bonfires_burning;public static int block_bonfires_burning_blockID;
public static Block block_jar01;public static int block_jar01_blockID;
public static Block block_pipes;public static int block_pipes_blockID;
public static Block block_cylinder;public static int block_cylinder_blockID;
public static Block block_mashine_waiter;public static int block_mashine_waiter_blockID;
public static Block block_rock_blocks;public static int block_rock_blocks_blockID;
public static Block block_glass_blocks;public static int block_glass_blocks_blockID;
public static Block block_wood_blocks;public static int block_wood_blocks_blockID;
public static Block block_ground_blocks;public static int block_ground_blocks_blockID;
public static Block block_sand_blocks;public static int block_sand_blocks_blockID;
public static Block block_cloth_blocks;public static int block_cloth_blocks_blockID;
public static Block block_metal_blocks;public static int block_metal_blocks_blockID;
public static Block block_vegetable_face;public static int block_vegetable_face_blockID;

//Items
public static Item items_for_furniture;public static int items_for_furniture_itemID;
public static ItemArmor armor_wool_colors_helmet;public static int armor_wool_colors_helmet_itemID;
public static ItemArmor armor_wool_colors_chest;public static int armor_wool_colors_chest_itemID;
public static ItemArmor armor_wool_colors_leggin;public static int armor_wool_colors_leggin_itemID;
public static ItemArmor armor_wool_colors_boot;public static int armor_wool_colors_boot_itemID;
public static Item item_brick_colors;public static int item_brick_colors_itemID;
public static Item item_colored;public static int item_colored_itemID;
public static Item item_setup_block;public static int item_setup_block_itemID;
public static Item tool_brush;public static int tool_brush_itemID;
public static Item tool_airbrush;public static int tool_airbrush_itemID;
public static Item item_paint_can;public static int item_paint_can_itemID;
public static Item item_backpack;public static int item_backpack_itemID;
public static Item item_filter_charcoal;public static int item_filter_charcoal_itemID;
public static Item item_kitchenware;public static int item_kitchenware_itemID;
public static ItemArmor armor_costumes_helmet;public static int armor_costumes_helmet_itemID;
public static ItemArmor armor_costumes_chest;public static int armor_costumes_chest_itemID;
public static ItemArmor armor_costumes_leggin;public static int armor_costumes_leggin_itemID;
public static ItemArmor armor_costumes_boot;public static int armor_costumes_boot_itemID;
public static ItemArmor armor_masks;public static int armor_masks_itemID;
public static ItemArmor armor_backpacks;public static int armor_backpacks_itemID;
public static Item item_particles_gun;public static int item_particles_gun_itemID;
public static ItemArmor armor_medieval_helmet;public static int armor_medieval_helmet_itemID;
public static ItemArmor armor_medieval_chest;public static int armor_medieval_chest_itemID;
public static ItemArmor armor_medieval_leggin;public static int armor_medieval_leggin_itemID;
public static ItemArmor armor_medieval_boot;public static int armor_medieval_boot_itemID;
public static ItemArmor armor_new_helmet;public static int armor_new_helmet_itemID;
public static ItemArmor armor_new_chest;public static int armor_new_chest_itemID;
public static ItemArmor armor_new_leggin;public static int armor_new_leggin_itemID;
public static ItemArmor armor_new_boot;public static int armor_new_boot_itemID;

//Blocks
public static int renderBlockCnstorBlockModelID;
public static int renderBlockCnstorAngleModelID;
public static int renderBlockCnstorFenceModelID;
public static int render_block_lights_modelID;
public static int renderBlockLampsOnModelID;
public static int renderBlockLampsOffModelID;
public static int renderBlockLamps2OnModelID;
public static int renderBlockLamps2OffModelID;
public static int renderBlockCandleModelID;
public static int renderBlockCrystalsModelID;
public static int renderBlockBarrelsModelID;
public static int renderBlockBookshelfModelID;
public static int renderBlockTableModelID;
public static int renderBlockChairModelID;
public static int renderBlockWardrobeModelID;
public static int renderBlockMincerModelID;
public static int renderBlockArmChairModelID;
public static int renderBlockBlenderModelID;
public static int renderBlockGrillsModelID;
public static int renderBlockBoxParticlesModelID;
public static int renderBlockBallsModelID;
public static int render_block_jar01_modelID;
public static int render_block_pipes_modelID;
public static int render_block_cylinder_modelID;
public static int render_block_mashine_waiter_modelID;

//GUI
//public static int guiID = 0;
public static int guiFurnitureMachines = 1;
public static int guiBookshelf = 16;
public static int guiMincer = 17;
public static int guiGrills = 18;
public static int gui_mashine_water = 19;
public static int guiBackpack = 20;


public void init() {
TickRegistry.registerTickHandler(new TickHandlerPackFurnitureServer(), Side.SERVER);

new ListFurniture();

//Blocks
block_furniture_machines = new BlockFurnitureMachines(block_furniture_machines_blockID);
block_cnstor_block = new BlockCnstorBlock(block_cnstor_block_blockID);
block_cnstor_angle = new BlockCnstorAngle(block_cnstor_angle_blockID);
block_cnstor_half = new BlockCnstorHalf(block_cnstor_half_blockID);
block_cnstor_button = new BlockCnstorButton(block_cnstor_button_blockID);
block_cnstor_lever = new BlockCnstorLever(block_cnstor_lever_blockID);
block_cnstor_stairs = new BlockCnstorStairs(block_cnstor_stairs_blockID);
block_cnstor_fence = new BlockCnstorFence(block_cnstor_fence_blockID);
block_cnstor_wall = new BlockCnstorWall(block_cnstor_wall_blockID);
block_cnstor_door = new BlockCnstorDoor(block_cnstor_door_blockID);
block_cnstor_bed = new BlockCnstorBed(block_cnstor_bed_blockID);

air_light_0 = new AirLight(air_light_0_blockID).setLightValue(0.0F);
air_light_1 = new AirLight(air_light_1_blockID).setLightValue(0.0625F);
air_light_2 = new AirLight(air_light_2_blockID).setLightValue(0.125F);
air_light_3 = new AirLight(air_light_3_blockID).setLightValue(0.1875F);
air_light_4 = new AirLight(air_light_4_blockID).setLightValue(0.25F);
air_light_5 = new AirLight(air_light_5_blockID).setLightValue(0.3125F);
air_light_6 = new AirLight(air_light_6_blockID).setLightValue(0.375F);
air_light_7 = new AirLight(air_light_7_blockID).setLightValue(0.4375F);
air_light_8 = new AirLight(air_light_8_blockID).setLightValue(0.5F);
air_light_9 = new AirLight(air_light_9_blockID).setLightValue(0.5625F);
air_light_10 = new AirLight(air_light_10_blockID).setLightValue(0.625F);
air_light_11 = new AirLight(air_light_11_blockID).setLightValue(0.6875F);
air_light_12 = new AirLight(air_light_12_blockID).setLightValue(0.75F);
air_light_13 = new AirLight(air_light_13_blockID).setLightValue(0.8125F);
air_light_14 = new AirLight(air_light_14_blockID).setLightValue(0.875F);
air_light_15 = new AirLight(air_light_15_blockID).setLightValue(0.9375F);
air_light_16 = new AirLight(air_light_16_blockID).setLightValue(1.0F);

block_light_0 = new BlockLight(block_light_0_blockID).setLightValue(0.0F).setCreativeTab(PackFurniture.proxy.tabFurniturePack);
block_light_1 = new BlockLight(block_light_1_blockID).setLightValue(0.0625F);
block_light_2 = new BlockLight(block_light_2_blockID).setLightValue(0.125F);
block_light_3 = new BlockLight(block_light_3_blockID).setLightValue(0.1875F);
block_light_4 = new BlockLight(block_light_4_blockID).setLightValue(0.25F);
block_light_5 = new BlockLight(block_light_5_blockID).setLightValue(0.3125F);
block_light_6 = new BlockLight(block_light_6_blockID).setLightValue(0.375F);
block_light_7 = new BlockLight(block_light_7_blockID).setLightValue(0.4375F);
block_light_8 = new BlockLight(block_light_8_blockID).setLightValue(0.5F);
block_light_9 = new BlockLight(block_light_9_blockID).setLightValue(0.5625F);
block_light_10 = new BlockLight(block_light_10_blockID).setLightValue(0.625F);
block_light_11 = new BlockLight(block_light_11_blockID).setLightValue(0.6875F);
block_light_12 = new BlockLight(block_light_12_blockID).setLightValue(0.75F);
block_light_13 = new BlockLight(block_light_13_blockID).setLightValue(0.8125F);
block_light_14 = new BlockLight(block_light_14_blockID).setLightValue(0.875F);
block_light_15 = new BlockLight(block_light_15_blockID).setLightValue(0.9375F);
block_light_16 = new BlockLight(block_light_16_blockID).setLightValue(1.0F);

block_lamps_click_on = new BlockLampsClicked(block_lamps_click_on_blockID, true).setUnlocalizedName("BlockLampsClickedOn");
block_lamps_click_off = new BlockLampsClicked(block_lamps_click_off_blockID, false).setUnlocalizedName("BlockLampsClickedOff");
block_lamps_on = new BlockLamps(block_lamps_on_blockID, true).setUnlocalizedName("BlockLampsOn");
block_lamps_off = new BlockLamps(block_lamps_off_blockID, false).setUnlocalizedName("BlockLampsOff");
block_lamps_on_invert = new BlockLampsInvert(block_lamps_on_invert_blockID, true).setUnlocalizedName("BlockLampsInvertOn");
block_lamps_off_invert = new BlockLampsInvert(block_lamps_off_invert_blockID, false).setUnlocalizedName("BlockLampsInvertOff");
block_model_lamps_click_on = new BlockModelLampsClickedOn(block_model_lamps_click_on_blockID);
block_model_lamps_click_off = new BlockModelLampsClickedOff(block_model_lamps_click_off_blockID);
block_model_lamps_on = new BlockModelLampsOn(block_model_lamps_on_blockID);
block_model_lamps_off = new BlockModelLampsOff(block_model_lamps_off_blockID);
block_model_lamps_on_invert = new BlockModelLampsOnInvert(block_model_lamps_on_invert_blockID);
block_model_lamps_off_invert = new BlockModelLampsOffInvert(block_model_lamps_off_invert_blockID);
block_model_lamps2_click_on = new BlockModelLamps2ClickedOn(block_model_lamps2_click_on_blockID);
block_model_lamps2_click_off = new BlockModelLamps2ClickedOff(block_model_lamps2_click_off_blockID);
block_model_lamps2_on = new BlockModelLamps2On(block_model_lamps2_on_blockID);
block_model_lamps2_off = new BlockModelLamps2Off(block_model_lamps2_off_blockID);
block_model_lamps2_on_invert = new BlockModelLamps2OnInvert(block_model_lamps2_on_invert_blockID);
block_model_lamps2_off_invert = new BlockModelLamps2OffInvert(block_model_lamps2_off_invert_blockID);
block_stone_colona1_colors = new BlockStoneColona1Colors(block_stone_colona1_colors_blockID);
block_stone_colona2_colors = new BlockStoneColona2Colors(block_stone_colona2_colors_blockID);
block_stone_colona3_colors = new BlockStoneColona3Colors(block_stone_colona3_colors_blockID);
block_stone_colona4_colors = new BlockStoneColona4Colors(block_stone_colona4_colors_blockID);
block_candle = new BlockCandle(block_candle_blockID).setLightValue(0.0F);
block_candle_light = new BlockCandle(block_candle_light_blockID).setLightValue(0.5F);
block_crystals = new BlockCrystals(block_crystals_blockID);
block_barrels = new BlockBarrels(block_barrels_blockID);
block_bookshelf = new BlockBookshelf(block_bookshelf_blockID);
block_table = new BlockTable(block_table_blockID);
block_chair = new BlockChair(block_chair_blockID);
block_wardrobe = new BlockWardrobe(block_wardrobe_blockID);
block_mincer = new BlockMincer(block_mincer_blockID);
block_arm_chair = new BlockArmChair(block_arm_chair_blockID);
block_blender = new BlockBlender(block_blender_blockID);
block_grills = new BlockGrills(block_grills_blockID);
block_box_particles = new BlockBoxParticles(block_box_particles_blockID);
block_balls = new BlockBalls(block_balls_blockID);
block_bonfires = new BlockBonfires(block_bonfires_blockID).setLightValue(0.0F);
block_bonfires_burning = new BlockBonfires(block_bonfires_burning_blockID).setLightValue(0.75F);
block_jar01 = new BlockJar01(block_jar01_blockID);
block_pipes = new BlockPipes(block_pipes_blockID);
block_cylinder = new BlockCylinder(block_cylinder_blockID);
block_mashine_waiter = new BlockMashineWater(block_mashine_waiter_blockID);
block_rock_blocks = new BlockRockBlocks(block_rock_blocks_blockID);
block_glass_blocks = new BlockGlassBlocks(block_glass_blocks_blockID);
block_wood_blocks = new BlockWoodBlocks(block_wood_blocks_blockID);
block_ground_blocks = new BlockGroundBlocks(block_ground_blocks_blockID);
block_sand_blocks = new BlockSandBlocks(block_sand_blocks_blockID);
block_cloth_blocks = new BlockClothBlocks(block_cloth_blocks_blockID);
block_metal_blocks = new BlockMetalBlocks(block_metal_blocks_blockID);
block_vegetable_face = new BlockVegetableFace(block_vegetable_face_blockID);

//Items
items_for_furniture = new ItemsFurniture(items_for_furniture_itemID);
armor_wool_colors_helmet = (ItemArmor)(new ArmorWoolColors(armor_wool_colors_helmet_itemID, CLOTHWOOL, 0, 0).setUnlocalizedName("ArmorWoolColorsHelmet"));
armor_wool_colors_chest = (ItemArmor)(new ArmorWoolColors(armor_wool_colors_chest_itemID, CLOTHWOOL, 0, 1).setUnlocalizedName("ArmorWoolColorsChest"));
armor_wool_colors_leggin = (ItemArmor)(new ArmorWoolColors(armor_wool_colors_leggin_itemID, CLOTHWOOL, 0, 2).setUnlocalizedName("ArmorWoolColorsLeggin"));
armor_wool_colors_boot = (ItemArmor)(new ArmorWoolColors(armor_wool_colors_boot_itemID, CLOTHWOOL, 0, 3).setUnlocalizedName("ArmorWoolColorsBoot"));
item_brick_colors = new ItemBrickColors(item_brick_colors_itemID);
item_colored = new ItemColored(item_colored_itemID);
item_setup_block = new ItemSetupBlock(item_setup_block_itemID);
tool_brush = new ToolBrush(tool_brush_itemID);
tool_airbrush = new ToolAirBrush(tool_airbrush_itemID);
item_paint_can = new ItemPaintCan(item_paint_can_itemID);
item_backpack = new ItemBackpack(item_backpack_itemID);
item_filter_charcoal = new ItemFilterCharcoal(item_filter_charcoal_itemID);
item_kitchenware = new ItemKitchenware(item_kitchenware_itemID);
armor_costumes_helmet = (ItemArmor) new ArmorCostumes(armor_costumes_helmet_itemID, COSTUME, 0, 0).setUnlocalizedName("armor_costumes_helmet");
armor_costumes_chest = (ItemArmor) new ArmorCostumes(armor_costumes_chest_itemID, COSTUME, 0, 1).setUnlocalizedName("armor_costumes_chest");
armor_costumes_leggin = (ItemArmor) new ArmorCostumes(armor_costumes_leggin_itemID, COSTUME, 0, 2).setUnlocalizedName("armor_costumes_leggin");
armor_costumes_boot = (ItemArmor) new ArmorCostumes(armor_costumes_boot_itemID, COSTUME, 0, 3).setUnlocalizedName("armor_costumes_boot");
armor_masks = new ArmorMasks(armor_masks_itemID);
armor_backpacks = new ArmorBackpacks(armor_backpacks_itemID);
item_particles_gun = new ItemParticlesGun(item_particles_gun_itemID);
armor_medieval_helmet = (ItemArmor) new ArmorMedieval(armor_medieval_helmet_itemID, COSTUME, 0, 0).setUnlocalizedName("armor_medieval_helmet");
armor_medieval_chest = (ItemArmor) new ArmorMedieval(armor_medieval_chest_itemID, COSTUME, 0, 1).setUnlocalizedName("armor_medieval_chest");
armor_medieval_leggin = (ItemArmor) new ArmorMedieval(armor_medieval_leggin_itemID, COSTUME, 0, 2).setUnlocalizedName("armor_medieval_leggin");
armor_medieval_boot = (ItemArmor) new ArmorMedieval(armor_medieval_boot_itemID, COSTUME, 0, 3).setUnlocalizedName("armor_medieval_boot");
armor_new_helmet = (ItemArmor) new ArmorNew(armor_new_helmet_itemID, COSTUME, 0, 0).setUnlocalizedName("armor_new_helmet");
armor_new_chest = (ItemArmor) new ArmorNew(armor_new_chest_itemID, COSTUME, 0, 1).setUnlocalizedName("armor_new_chest");
armor_new_leggin = (ItemArmor) new ArmorNew(armor_new_leggin_itemID, COSTUME, 0, 2).setUnlocalizedName("armor_new_leggin");
armor_new_boot = (ItemArmor) new ArmorNew(armor_new_boot_itemID, COSTUME, 0, 3).setUnlocalizedName("armor_new_boot");

//Blocks
renderBlockCnstorBlockModelID = -1;
renderBlockCnstorAngleModelID = -1;
renderBlockCnstorFenceModelID = -1;
render_block_lights_modelID = -1;
renderBlockLampsOnModelID = -1;
renderBlockLampsOffModelID = -1;
renderBlockLamps2OnModelID = -1;
renderBlockLamps2OffModelID = -1;
renderBlockCandleModelID = -1;
renderBlockCrystalsModelID = -1;
renderBlockBarrelsModelID = -1;
renderBlockBookshelfModelID = -1;
renderBlockTableModelID = -1;
renderBlockChairModelID = -1;
renderBlockWardrobeModelID = -1;
renderBlockMincerModelID = -1;
renderBlockArmChairModelID = -1;
renderBlockBlenderModelID = -1;
renderBlockGrillsModelID = -1;
renderBlockBoxParticlesModelID = -1;
renderBlockBallsModelID = -1;
render_block_jar01_modelID = -1;
render_block_pipes_modelID = -1;
render_block_cylinder_modelID = -1;
render_block_mashine_waiter_modelID = -1;

//Blocks
GameRegistry.registerBlock(block_furniture_machines, "BlockMachines");
GameRegistry.registerBlock(block_cnstor_block, ItemBlockCnstorBlock.class, "BlockCnstorBlock");
GameRegistry.registerBlock(block_cnstor_angle, ItemBlockCnstorAngle.class, "BlockCnstorAngle");
GameRegistry.registerBlock(block_cnstor_half, ItemBlockCnstorHalf.class, "BlockCnstorHalf");
GameRegistry.registerBlock(block_cnstor_button, ItemBlockCnstorButton.class, "BlockCnstorButton");
GameRegistry.registerBlock(block_cnstor_lever, ItemBlockCnstorLever.class, "BlockCnstorLever");
GameRegistry.registerBlock(block_cnstor_stairs, ItemBlockCnstorStairs.class, "BlockCnstorStairs");
GameRegistry.registerBlock(block_cnstor_fence, ItemBlockCnstorFence.class, "BlockCnstorFence");
GameRegistry.registerBlock(block_cnstor_wall, ItemBlockCnstorWall.class, "BlockCnstorWall");
GameRegistry.registerBlock(block_cnstor_door, ItemBlockCnstorDoor.class, "BlockCnstorDoor");
GameRegistry.registerBlock(block_cnstor_bed, ItemBlockCnstorBed.class, "BlockCnstorBed");

GameRegistry.registerBlock(air_light_0, "AirLight0");
GameRegistry.registerBlock(air_light_1, "AirLight1");
GameRegistry.registerBlock(air_light_2, "AirLight2");
GameRegistry.registerBlock(air_light_3, "AirLight3");
GameRegistry.registerBlock(air_light_4, "AirLight4");
GameRegistry.registerBlock(air_light_5, "AirLight5");
GameRegistry.registerBlock(air_light_6, "AirLight6");
GameRegistry.registerBlock(air_light_7, "AirLight7");
GameRegistry.registerBlock(air_light_8, "AirLight8");
GameRegistry.registerBlock(air_light_9, "AirLight9");
GameRegistry.registerBlock(air_light_10, "AirLight10");
GameRegistry.registerBlock(air_light_11, "AirLight11");
GameRegistry.registerBlock(air_light_12, "AirLight12");
GameRegistry.registerBlock(air_light_13, "AirLight13");
GameRegistry.registerBlock(air_light_14, "AirLight14");
GameRegistry.registerBlock(air_light_15, "AirLight15");
GameRegistry.registerBlock(air_light_16, "AirLight16");

GameRegistry.registerBlock(block_light_0, "BlockLight0");
GameRegistry.registerBlock(block_light_1, "BlockLight1");
GameRegistry.registerBlock(block_light_2, "BlockLight2");
GameRegistry.registerBlock(block_light_3, "BlockLight3");
GameRegistry.registerBlock(block_light_4, "BlockLight4");
GameRegistry.registerBlock(block_light_5, "BlockLight5");
GameRegistry.registerBlock(block_light_6, "BlockLight6");
GameRegistry.registerBlock(block_light_7, "BlockLight7");
GameRegistry.registerBlock(block_light_8, "BlockLight8");
GameRegistry.registerBlock(block_light_9, "BlockLight9");
GameRegistry.registerBlock(block_light_10, "BlockLight10");
GameRegistry.registerBlock(block_light_11, "BlockLight11");
GameRegistry.registerBlock(block_light_12, "BlockLight12");
GameRegistry.registerBlock(block_light_13, "BlockLight13");
GameRegistry.registerBlock(block_light_14, "BlockLight14");
GameRegistry.registerBlock(block_light_15, "BlockLight15");
GameRegistry.registerBlock(block_light_16, "BlockLight16");

GameRegistry.registerBlock(block_lamps_click_on, ItemBlockLampsClickOn.class, "BlockLampsClickOn");
GameRegistry.registerBlock(block_lamps_click_off, ItemBlockLampsClickOff.class, "BlockLampsClickOff");
GameRegistry.registerBlock(block_lamps_on, ItemBlockLampsOn.class, "BlockLampsOn");
GameRegistry.registerBlock(block_lamps_off, ItemBlockLampsOff.class, "BlockLampsOff");
GameRegistry.registerBlock(block_lamps_on_invert, ItemBlockLampsOnInvert.class, "BlockLampsOnInvert");
GameRegistry.registerBlock(block_lamps_off_invert, ItemBlockLampsOffInvert.class, "BlockLampsOffInvert");
GameRegistry.registerBlock(block_model_lamps_click_on, ItemBlockModelLampsClickOn.class, "BlockModelLampsClickOn");
GameRegistry.registerBlock(block_model_lamps_click_off, ItemBlockModelLampsClickOff.class, "BlockModelLampsClickOff");
GameRegistry.registerBlock(block_model_lamps_on, ItemBlockModelLampsOn.class, "BlockModelLampsOn");
GameRegistry.registerBlock(block_model_lamps_off, ItemBlockModelLampsOff.class, "BlockModelLampsOff");
GameRegistry.registerBlock(block_model_lamps_on_invert, ItemBlockModelLampsOnInvert.class, "BlockModelLampsOnInvert");
GameRegistry.registerBlock(block_model_lamps_off_invert, ItemBlockModelLampsOffInvert.class, "BlockModelLampsOffInvert");
GameRegistry.registerBlock(block_model_lamps2_click_on, ItemBlockModelLamps2ClickOn.class, "BlockModelLamps2ClickOn");
GameRegistry.registerBlock(block_model_lamps2_click_off, ItemBlockModelLamps2ClickOff.class, "BlockModelLamps2ClickOff");
GameRegistry.registerBlock(block_model_lamps2_on, ItemBlockModelLamps2On.class, "BlockModelLamps2On");
GameRegistry.registerBlock(block_model_lamps2_off, ItemBlockModelLamps2Off.class, "BlockModelLamps2Off");
GameRegistry.registerBlock(block_model_lamps2_on_invert, ItemBlockModelLamps2OnInvert.class, "BlockModelLamps2OnInvert");
GameRegistry.registerBlock(block_model_lamps2_off_invert, ItemBlockModelLamps2OffInvert.class, "BlockModelLamps2OffInvert");
GameRegistry.registerBlock(block_stone_colona1_colors, ItemBlockStoneColona1Colors.class, "StoneColona1Colors");
GameRegistry.registerBlock(block_stone_colona2_colors, ItemBlockStoneColona2Colors.class, "StoneColona2Colors");
GameRegistry.registerBlock(block_stone_colona3_colors, ItemBlockStoneColona3Colors.class, "StoneColona3Colors");
GameRegistry.registerBlock(block_stone_colona4_colors, ItemBlockStoneColona4Colors.class, "StoneColona4Colors");
GameRegistry.registerBlock(block_candle, ItemBlockCandle.class, "BlockCandle");
GameRegistry.registerBlock(block_candle_light, ItemBlockCandle.class, "BlockCandleLight");
GameRegistry.registerBlock(block_crystals, ItemBlockCrystals.class, "BlockCrystals");
GameRegistry.registerBlock(block_barrels, ItemBlockBarrels.class, "BlockBarrels");
GameRegistry.registerBlock(block_bookshelf, ItemBlockBookshelf.class, "BlockBookshelf");
GameRegistry.registerBlock(block_table, ItemBlockTable.class, "BlockTable");
GameRegistry.registerBlock(block_chair, ItemBlockChair.class, "BlockChair");
GameRegistry.registerBlock(block_wardrobe, ItemBlockWardrobe.class, "BlockWardrobe");
GameRegistry.registerBlock(block_mincer, "BlockMincer");
GameRegistry.registerBlock(block_arm_chair, ItemBlockArmChair.class, "BlockArmChair");
GameRegistry.registerBlock(block_blender, ItemBlockBlender.class, "BlockBlender");
GameRegistry.registerBlock(block_grills, ItemBlockGrills.class, "BlockGrills");
GameRegistry.registerBlock(block_box_particles, ItemBlockBoxParticles.class, "BlockBoxParticles");
GameRegistry.registerBlock(block_balls, "BlockBalls");
GameRegistry.registerBlock(block_bonfires, "BlockBonfires");
GameRegistry.registerBlock(block_bonfires_burning, "BlockBonfiresBurning");
GameRegistry.registerBlock(block_jar01, "BlockJar01");
GameRegistry.registerBlock(block_pipes, "BlockPipes");
GameRegistry.registerBlock(block_cylinder, "BlockCylinder");
GameRegistry.registerBlock(block_mashine_waiter, "BlockMashineWater");
GameRegistry.registerBlock(block_rock_blocks, ItemBlockRockBlocks.class, "BlockRockBlocks");
GameRegistry.registerBlock(block_glass_blocks, ItemBlockGlassBlocks.class, "BlockGlassBlocks");
GameRegistry.registerBlock(block_wood_blocks, ItemBlockWoodBlocks.class, "BlockWoodBlocks");
GameRegistry.registerBlock(block_ground_blocks, ItemBlockGroundBlocks.class, "BlockGroundBlocks");
GameRegistry.registerBlock(block_sand_blocks, ItemBlockSandBlocks.class, "BlockSandBlocks");
GameRegistry.registerBlock(block_cloth_blocks, ItemBlockClothBlocks.class, "BlockClothBlocks");
GameRegistry.registerBlock(block_metal_blocks, ItemBlockMetalBlocks.class, "BlockMetalBlocks");
GameRegistry.registerBlock(block_vegetable_face, "BlockVegetableFace");

//Items
GameRegistry.registerItem(items_for_furniture, "ItemsFurniture");
GameRegistry.registerItem(armor_wool_colors_helmet, "ArmorWoolColorsHelmet");
GameRegistry.registerItem(armor_wool_colors_chest, "ArmorWoolColorsChest");
GameRegistry.registerItem(armor_wool_colors_leggin, "ArmorWoolColorsLeggin");
GameRegistry.registerItem(armor_wool_colors_boot, "ArmorWoolColorsBoot");
GameRegistry.registerItem(item_brick_colors, "ItemBrickColors");
GameRegistry.registerItem(item_colored, "ItemColored");
GameRegistry.registerItem(item_setup_block, "ItemSetupBlock");
GameRegistry.registerItem(tool_brush, "IoolBrush");
GameRegistry.registerItem(tool_airbrush, "ToolAirBrush");
GameRegistry.registerItem(item_paint_can, "ItemPaintCan");
GameRegistry.registerItem(item_backpack, "ItemBackpack");
GameRegistry.registerItem(item_filter_charcoal, "ItemFilterCharcoal");
GameRegistry.registerItem(item_kitchenware, "ItemKitchenware");
GameRegistry.registerItem(armor_costumes_helmet, "ArmorCostumesHelmet");
GameRegistry.registerItem(armor_costumes_chest, "ArmorCostumesChest");
GameRegistry.registerItem(armor_costumes_leggin, "ArmorCostumesLeggin");
GameRegistry.registerItem(armor_costumes_boot, "ArmorCostumesBoot");
GameRegistry.registerItem(armor_masks, "ArmorMasks");
GameRegistry.registerItem(armor_backpacks, "ArmorBackpacks");
GameRegistry.registerItem(item_particles_gun, "ItemParticlesGun");
GameRegistry.registerItem(armor_medieval_helmet, "ArmorMedievalHelmet");
GameRegistry.registerItem(armor_medieval_chest, "ArmorMedievalChest");
GameRegistry.registerItem(armor_medieval_leggin, "ArmorMedievalLeggin");
GameRegistry.registerItem(armor_medieval_boot, "ArmorMedievalBoot");
GameRegistry.registerItem(armor_new_helmet, "ArmorNewHelmet");
GameRegistry.registerItem(armor_new_chest, "ArmorNewChest");
GameRegistry.registerItem(armor_new_leggin, "ArmorNewLeggin");
GameRegistry.registerItem(armor_new_boot, "ArmorNewBoot");

GameRegistry.registerTileEntity(TEFurnitureMachines.class, "TEFurnitureMachines");
GameRegistry.registerTileEntity(TECnstorBlock.class, "TECnstorBlock");
GameRegistry.registerTileEntity(TEAngleMod.class, "TEAngleMod");
GameRegistry.registerTileEntity(TECnstorFence.class, "TECnstorFence");
GameRegistry.registerTileEntity(TECnstorDoors.class, "TECnstorDoors");
GameRegistry.registerTileEntity(TELights.class, "TELights");
GameRegistry.registerTileEntity(TELampsOn.class, "TELampsOn");
GameRegistry.registerTileEntity(TELampsOff.class, "TELampsOff");
GameRegistry.registerTileEntity(TELampsOn.class, "TELamps2On");
GameRegistry.registerTileEntity(TELamps2Off.class, "TELamps2Off");
GameRegistry.registerTileEntity(TECandle.class, "TECandle");
GameRegistry.registerTileEntity(TECrystals.class, "TECrystals");
GameRegistry.registerTileEntity(TEBarrels.class, "TEBarrels");
GameRegistry.registerTileEntity(TEBookshelf.class, "TEBookshelf");
GameRegistry.registerTileEntity(TETable.class, "TETable");
GameRegistry.registerTileEntity(TEChair.class, "TEChair");
GameRegistry.registerTileEntity(TEWardrobe.class, "TEWardrobe");
GameRegistry.registerTileEntity(TEMincer.class, "TEMincer");
GameRegistry.registerTileEntity(TEArmChair.class, "TEArmChair");
GameRegistry.registerTileEntity(TEBlender.class, "TEBlender");
GameRegistry.registerTileEntity(TEGrills.class, "TEGrills");
GameRegistry.registerTileEntity(TEBoxParticles.class, "TEBoxParticles");
GameRegistry.registerTileEntity(TEBalls.class, "TEBalls");
GameRegistry.registerTileEntity(TEJar01.class, "TEJar01");
GameRegistry.registerTileEntity(TEPipes.class, "TEPipes");
GameRegistry.registerTileEntity(TEMashineWater.class, "TEMashineWater");
GameRegistry.registerTileEntity(TEBlockBlocks.class, "TEBlockBlocks");
GameRegistry.registerTileEntity(TEBlockRockBlocks.class, "TEBlockRockBlocks");
GameRegistry.registerTileEntity(TEBlockGlassBlocks.class, "TEBlockGlassBlocks");
GameRegistry.registerTileEntity(TEBlockWoodBlocks.class, "TEBlockWoodBlocks");
GameRegistry.registerTileEntity(TEBlockGroundBlocks.class, "TEBlockGroundBlocks");
GameRegistry.registerTileEntity(TEBlockSandBlocks.class, "TEBlockSandBlocks");
GameRegistry.registerTileEntity(TEBlockClothBlocks.class, "TEBlockClothBlocks");
GameRegistry.registerTileEntity(TEBlockMetalBlocks.class, "TEBlockMetalBlocks");
GameRegistry.registerTileEntity(TEBlockVegetableFace.class, "TEBlockVegetableFace");

OreDictionary.registerOre("dyeBlack", new ItemStack(item_colored, 1, 0));
OreDictionary.registerOre("dyeBlue", new ItemStack(item_colored, 1, 1));
OreDictionary.registerOre("dyeBrown", new ItemStack(item_colored, 1, 2));
OreDictionary.registerOre("dyeCyan", new ItemStack(item_colored, 1, 3));
OreDictionary.registerOre("dyeGray", new ItemStack(item_colored, 1, 4));
OreDictionary.registerOre("dyeGreen", new ItemStack(item_colored, 1, 5));
OreDictionary.registerOre("dyeLightBlue", new ItemStack(item_colored, 1, 6));
OreDictionary.registerOre("dyeLightGray", new ItemStack(item_colored, 1, 7));
OreDictionary.registerOre("dyeLightGreen", new ItemStack(item_colored, 1, 8));
OreDictionary.registerOre("dyeLime", new ItemStack(item_colored, 1, 8));
OreDictionary.registerOre("dyeMagenta", new ItemStack(item_colored, 1, 9));
OreDictionary.registerOre("dyeOrange", new ItemStack(item_colored, 1, 10));
OreDictionary.registerOre("dyePink", new ItemStack(item_colored, 1, 11));
OreDictionary.registerOre("dyePurple", new ItemStack(item_colored, 1, 12));
OreDictionary.registerOre("dyeRed", new ItemStack(item_colored, 1, 13));
OreDictionary.registerOre("dyeWhite", new ItemStack(item_colored, 1, 14));
OreDictionary.registerOre("dyeYellow", new ItemStack(item_colored, 1, 15));

OreDictionary.registerOre("dyeBlack", new ItemStack(item_colored, 1, 16));
OreDictionary.registerOre("dyeBlue", new ItemStack(item_colored, 1, 17));
OreDictionary.registerOre("dyeBrown", new ItemStack(item_colored, 1, 18));
OreDictionary.registerOre("dyeCyan", new ItemStack(item_colored, 1, 19));
OreDictionary.registerOre("dyeGray", new ItemStack(item_colored, 1, 20));
OreDictionary.registerOre("dyeGreen", new ItemStack(item_colored, 1, 21));
OreDictionary.registerOre("dyeLightBlue", new ItemStack(item_colored, 1, 22));
OreDictionary.registerOre("dyeLightGray", new ItemStack(item_colored, 1, 23));
OreDictionary.registerOre("dyeLightGreen", new ItemStack(item_colored, 1, 24));
OreDictionary.registerOre("dyeLime", new ItemStack(item_colored, 1, 24));
OreDictionary.registerOre("dyeMagenta", new ItemStack(item_colored, 1, 25));
OreDictionary.registerOre("dyeOrange", new ItemStack(item_colored, 1, 26));
OreDictionary.registerOre("dyePink", new ItemStack(item_colored, 1, 27));
OreDictionary.registerOre("dyePurple", new ItemStack(item_colored, 1, 28));
OreDictionary.registerOre("dyeRed", new ItemStack(item_colored, 1, 29));
OreDictionary.registerOre("dyeWhite", new ItemStack(item_colored, 1, 30));
OreDictionary.registerOre("dyeYellow", new ItemStack(item_colored, 1, 31));

GameRegistry.addRecipe(new RecipeCnstorBlockColors());
GameRegistry.addRecipe(new RecipeArmorColor());
GameRegistry.registerCraftingHandler(new CraftFurnitureHandler());

GameRegistry.registerFuelHandler(new FuelHandlerFurniture());

NetworkRegistry.instance().registerGuiHandler(this, new HandlerGuiFurniture());

/*
TickRegistry.registerTickHandler(new TickClientHandler(), Side.CLIENT);
TickRegistry.registerTickHandler(new TickServerHandler(), Side.SERVER);
*/
Recipes_Furniture.list();
Recipes_Armor.list();

MinecraftForge.EVENT_BUS.register(new EventFurniture());

}

public void preInit(FMLPreInitializationEvent event) {

Configuration cfg = new Configuration(event.getSuggestedConfigurationFile());
cfg.load();
int idblock = 2200;
int iditem = 5200;
//Blocks
block_furniture_machines_blockID = cfg.getBlock("machines", idblock++).getInt();
block_cnstor_block_blockID = cfg.getBlock("cnstor_block", idblock++).getInt();
block_cnstor_angle_blockID = cfg.getBlock("cnstor_angle", idblock++).getInt();
block_cnstor_half_blockID = cfg.getBlock("cnstor_half", idblock++).getInt();
block_cnstor_button_blockID = cfg.getBlock("cnstor_button", idblock++).getInt();
block_cnstor_lever_blockID = cfg.getBlock("cnstor_lever", idblock++).getInt();
block_cnstor_stairs_blockID = cfg.getBlock("cnstor_stairs", idblock++).getInt();
block_cnstor_fence_blockID = cfg.getBlock("cnstor_fence", idblock++).getInt();
block_cnstor_wall_blockID = cfg.getBlock("cnstor_wall", idblock++).getInt();
block_cnstor_door_blockID = cfg.getBlock("door", idblock++).getInt();
block_cnstor_bed_blockID = cfg.getBlock("bed", idblock++).getInt();

air_light_0_blockID = cfg.getBlock("air_light_0", idblock++).getInt();
air_light_1_blockID = cfg.getBlock("air_light_1", idblock++).getInt();
air_light_2_blockID = cfg.getBlock("air_light_2", idblock++).getInt();
air_light_3_blockID = cfg.getBlock("air_light_3", idblock++).getInt();
air_light_4_blockID = cfg.getBlock("air_light_4", idblock++).getInt();
air_light_5_blockID = cfg.getBlock("air_light_5", idblock++).getInt();
air_light_6_blockID = cfg.getBlock("air_light_6", idblock++).getInt();
air_light_7_blockID = cfg.getBlock("air_light_7", idblock++).getInt();
air_light_8_blockID = cfg.getBlock("air_light_8", idblock++).getInt();
air_light_9_blockID = cfg.getBlock("air_light_9", idblock++).getInt();
air_light_10_blockID = cfg.getBlock("air_light_10", idblock++).getInt();
air_light_11_blockID = cfg.getBlock("air_light_11", idblock++).getInt();
air_light_12_blockID = cfg.getBlock("air_light_12", idblock++).getInt();
air_light_13_blockID = cfg.getBlock("air_light_13", idblock++).getInt();
air_light_14_blockID = cfg.getBlock("air_light_14", idblock++).getInt();
air_light_15_blockID = cfg.getBlock("air_light_15", idblock++).getInt();
air_light_16_blockID = cfg.getBlock("air_light_16", idblock++).getInt();

block_light_0_blockID = cfg.getBlock("block_light_0", idblock++).getInt();
block_light_1_blockID = cfg.getBlock("block_light_1", idblock++).getInt();
block_light_2_blockID = cfg.getBlock("block_light_2", idblock++).getInt();
block_light_3_blockID = cfg.getBlock("block_light_3", idblock++).getInt();
block_light_4_blockID = cfg.getBlock("block_light_4", idblock++).getInt();
block_light_5_blockID = cfg.getBlock("block_light_5", idblock++).getInt();
block_light_6_blockID = cfg.getBlock("block_light_6", idblock++).getInt();
block_light_7_blockID = cfg.getBlock("block_light_7", idblock++).getInt();
block_light_8_blockID = cfg.getBlock("block_light_8", idblock++).getInt();
block_light_9_blockID = cfg.getBlock("block_light_9", idblock++).getInt();
block_light_10_blockID = cfg.getBlock("block_light_10", idblock++).getInt();
block_light_11_blockID = cfg.getBlock("block_light_11", idblock++).getInt();
block_light_12_blockID = cfg.getBlock("block_light_12", idblock++).getInt();
block_light_13_blockID = cfg.getBlock("block_light_13", idblock++).getInt();
block_light_14_blockID = cfg.getBlock("block_light_14", idblock++).getInt();
block_light_15_blockID = cfg.getBlock("block_light_15", idblock++).getInt();
block_light_16_blockID = cfg.getBlock("block_light_16", idblock++).getInt();

block_lamps_click_on_blockID = cfg.getBlock("lamps_click_on", idblock++).getInt();
block_lamps_click_off_blockID = cfg.getBlock("lamps_click_off", idblock++).getInt();
block_lamps_on_blockID = cfg.getBlock("lamps_on", idblock++).getInt();
block_lamps_off_blockID = cfg.getBlock("lamps_off", idblock++).getInt();
block_lamps_on_invert_blockID = cfg.getBlock("lamps_on_invert", idblock++).getInt();
block_lamps_off_invert_blockID = cfg.getBlock("lamps_off_invert", idblock++).getInt();
block_model_lamps_click_on_blockID = cfg.getBlock("model_lamps_click_on", idblock++).getInt();
block_model_lamps_click_off_blockID = cfg.getBlock("model_lamps_click_off", idblock++).getInt();
block_model_lamps_on_blockID = cfg.getBlock("model_lamps_on", idblock++).getInt();
block_model_lamps_off_blockID = cfg.getBlock("model_lamps_off", idblock++).getInt();
block_model_lamps_on_invert_blockID = cfg.getBlock("model_lamps_on_invert", idblock++).getInt();
block_model_lamps_off_invert_blockID = cfg.getBlock("model_lamps_off_invert", idblock++).getInt();
block_model_lamps2_click_on_blockID = cfg.getBlock("model_lamps2_click_on", idblock++).getInt();
block_model_lamps2_click_off_blockID = cfg.getBlock("model_lamps2_click_off", idblock++).getInt();
block_model_lamps2_on_blockID = cfg.getBlock("model_lamps2_on", idblock++).getInt();
block_model_lamps2_off_blockID = cfg.getBlock("model_lamps2_off", idblock++).getInt();
block_model_lamps2_on_invert_blockID = cfg.getBlock("model_lamps2_on_invert", idblock++).getInt();
block_model_lamps2_off_invert_blockID = cfg.getBlock("model_lamps2_off_invert", idblock++).getInt();
block_stone_colona1_colors_blockID = cfg.getBlock("stone_colona1_colors", idblock++).getInt();
block_stone_colona2_colors_blockID = cfg.getBlock("stone_colona2_colors", idblock++).getInt();
block_stone_colona3_colors_blockID = cfg.getBlock("stone_colona3_colors", idblock++).getInt();
block_stone_colona4_colors_blockID = cfg.getBlock("stone_colona4_colors", idblock++).getInt();
block_candle_blockID = cfg.getBlock("candle", idblock++).getInt();
block_candle_light_blockID = cfg.getBlock("candleLight", idblock++).getInt();
block_crystals_blockID = cfg.getBlock("crystals", idblock++).getInt();
block_barrels_blockID = cfg.getBlock("barrels", idblock++).getInt();
block_bookshelf_blockID = cfg.getBlock("bookshelf", idblock++).getInt();
block_table_blockID = cfg.getBlock("table", idblock++).getInt();
block_chair_blockID = cfg.getBlock("chair", idblock++).getInt();
block_wardrobe_blockID = cfg.getBlock("wardrobe", idblock++).getInt();
block_mincer_blockID = cfg.getBlock("mincer", idblock++).getInt();
block_arm_chair_blockID = cfg.getBlock("armchair", idblock++).getInt();
block_blender_blockID = cfg.getBlock("blender", idblock++).getInt();
block_grills_blockID = cfg.getBlock("grills", idblock++).getInt();
block_box_particles_blockID = cfg.getBlock("box_particles", idblock++).getInt();
block_balls_blockID = cfg.getBlock("balls", idblock++).getInt();
block_bonfires_blockID = cfg.getBlock("block_bonfires", idblock++).getInt();
block_bonfires_burning_blockID = cfg.getBlock("block_bonfires_burning", idblock++).getInt();
block_jar01_blockID = cfg.getBlock("block_jar01", idblock++).getInt();
block_pipes_blockID = cfg.getBlock("block_pipes", idblock++).getInt();
block_cylinder_blockID = cfg.getBlock("block_cylinder", idblock++).getInt();
block_mashine_waiter_blockID = cfg.getBlock("block_mashine_waiter", idblock++).getInt();
block_rock_blocks_blockID = cfg.getBlock("block_rock_blocks", idblock++).getInt();
block_glass_blocks_blockID = cfg.getBlock("block_glass_blocks", idblock++).getInt();
block_wood_blocks_blockID = cfg.getBlock("block_wood_blocks", idblock++).getInt();
block_ground_blocks_blockID = cfg.getBlock("block_ground_blocks", idblock++).getInt();
block_sand_blocks_blockID = cfg.getBlock("block_sand_blocks", idblock++).getInt();
block_cloth_blocks_blockID = cfg.getBlock("block_cloth_blocks", idblock++).getInt();
block_metal_blocks_blockID = cfg.getBlock("block_metal_blocks", idblock++).getInt();
block_vegetable_face_blockID = cfg.getBlock("block_vegetable_face", idblock++).getInt();

//Items
items_for_furniture_itemID = cfg.getItem("items_for_furniture", iditem++).getInt();
armor_wool_colors_helmet_itemID = cfg.getItem("armor_wool_colors_helmet", iditem++).getInt();
armor_wool_colors_chest_itemID = cfg.getItem("armor_wool_colors_chest", iditem++).getInt();
armor_wool_colors_leggin_itemID = cfg.getItem("armor_wool_colors_leggin", iditem++).getInt();
armor_wool_colors_boot_itemID = cfg.getItem("armor_wool_colors_boot", iditem++).getInt();
item_brick_colors_itemID = cfg.getItem("brick_colors", iditem++).getInt();
item_colored_itemID = cfg.getItem("colored", iditem++).getInt();
item_setup_block_itemID = cfg.getItem("setup_block", iditem++).getInt();
tool_brush_itemID = cfg.getItem("brush", iditem++).getInt();
tool_airbrush_itemID = cfg.getItem("air_brush", iditem++).getInt();
item_paint_can_itemID = cfg.getItem("paint_can", iditem++).getInt();
item_backpack_itemID = cfg.getItem("item_backpack", iditem++).getInt();
item_filter_charcoal_itemID = cfg.getItem("item_filter_charcoal", iditem++).getInt();
item_kitchenware_itemID = cfg.getItem("item_kitchenware", iditem++).getInt();
armor_costumes_helmet_itemID = cfg.getItem("armor_costumes_helmet", iditem++).getInt();
armor_costumes_chest_itemID = cfg.getItem("armor_costumes_chest", iditem++).getInt();
armor_costumes_leggin_itemID = cfg.getItem("armor_costumes_leggin", iditem++).getInt();
armor_costumes_boot_itemID = cfg.getItem("armor_costumes_boot", iditem++).getInt();
armor_masks_itemID = cfg.getItem("armor_masks", iditem++).getInt();
armor_backpacks_itemID = cfg.getItem("armor_backpacks", iditem++).getInt();
item_particles_gun_itemID = cfg.getItem("item_particles_gun", iditem++).getInt();
armor_medieval_helmet_itemID = cfg.getItem("armor_medieval_helmet", iditem++).getInt();
armor_medieval_chest_itemID = cfg.getItem("armor_medieval_chest", iditem++).getInt();
armor_medieval_leggin_itemID = cfg.getItem("armor_medieval_leggin", iditem++).getInt();
armor_medieval_boot_itemID = cfg.getItem("armor_medieval_boot", iditem++).getInt();
armor_new_helmet_itemID = cfg.getItem("armor_new_helmet", iditem++).getInt();
armor_new_chest_itemID = cfg.getItem("armor_new_chest", iditem++).getInt();
armor_new_leggin_itemID = cfg.getItem("armor_new_leggin", iditem++).getInt();
armor_new_boot_itemID = cfg.getItem("armor_new_boot", iditem++).getInt();
cfg.save();
}

}
