package smt.decorations

import com.google.common.collect.Lists
import cpw.mods.fml.common.event.FMLPreInitializationEvent
import cpw.mods.fml.common.{ModMetadata, Mod}

/**
 * Decorations module, add some useful and nice stuffs
 * @author Dragon2488
 */
@Mod(name = "SMT: Decorations", modid = "SMT|DECORATIONS", version = "0.11a", dependencies = "required-after:SMT|CORE", useMetadata = true)
object SMTDecorations {

  @Mod.EventHandler
  def preInit(event: FMLPreInitializationEvent): Unit = {
    applyMetadata(event.getModMetadata)
  }

  def applyMetadata(meta: ModMetadata) {
    meta.url = "http://forum.mcmodding.ru/viewtopic.php?id=4"
    meta.authorList = Lists.newArrayList("Dragon2488")
    meta.description = "SMT: Decorations add some nice and useful stuffs"
    meta.logoFile = "/smt_decorations_logo.png"
    meta.autogenerated = false
  }


}
